run-name: Python Script Trigger - ${{ github.event.inputs.trigger_id }}

on:
  workflow_dispatch:
    inputs:
      trigger_id:
        description: 'Unique identifier for the workflow.'
        required: true

jobs:
  run-python-script:
    runs-on: self-hosted

    steps:
      - name: Echo Hello World
        run: echo "Hello, World!"

      - name: Save Output to File
        run: echo "Hello from GitHub Actions!" > output.txt

      - name: Upload Output
        uses: actions/upload-artifact@v4
        with:
          name: workflow-output
          path: output.txt
