name: Python Script Trigger

on:
  workflow_dispatch:
    inputs:
      trigger_id:
        description: 'Unique identifier for the workflow.'
        required: true

jobs:
  run-python-script:
    runs-on: self-hosted

    steps:
      - name: Echo Hello World
        run: echo "Hello, World!"
